### ISSUE TITLE
Create H2 element

### ISSUE THREAD

**Issue by LiefJamesCain** [Dragon-Coder/project-team-training#2]
Hey Kelsey can you add in an H2 so I can test my js? Thanks! 

PS: don't know if this is how this should be used, but here we go!

**Comment by kelsey-white** [comment]
I added in an H1, H2, and paragraph text. It should be accessible here for you now, let me know if it's not! Still sorting out how to use all of this haha.

**Comment by LiefJamesCain** [comment]
I forgot: we also need to reference the JS sheet in the HTML sheet!
Not sure if we are using this right, but it seems to be working! Maybe Chris will have more input ...
